version: '3.6'
services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - s3
      - sftp-server
    tty: true
    command: "/app/bin/cache"
    container_name: 'cache-cli'
    volumes:
      - go-pkg-cache:/go
      - .:/app
  s3:
    image: quay.io/minio/minio:RELEASE.2021-09-15T04-54-25Z
    container_name: 's3'
    ports:
      - 9000:9000
    entrypoint: sh
    command: -c 'mkdir -p /tmp/s3-data/semaphore-cache && minio server /tmp/s3-data'
  sftp-server:
    container_name: sftp-server
    ports:
      - "2222:22"
    build:
      context: .
      dockerfile: Dockerfile.sftp_server
volumes:
  go-pkg-cache:
    driver: local